// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOCJdvg2PcTBDiWAPZIH_HSXLkVzg0Es',
    appId: '1:736853854569:web:3dec6fca2770a0b52455f8',
    messagingSenderId: '736853854569',
    projectId: 'coin-control-44df7',
    authDomain: 'coin-control-44df7.firebaseapp.com',
    storageBucket: 'coin-control-44df7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDugkx15hjziYDTEbZ6FKK4vhYz1OGBsy8',
    appId: '1:736853854569:android:d0b804626c6ff0632455f8',
    messagingSenderId: '736853854569',
    projectId: 'coin-control-44df7',
    storageBucket: 'coin-control-44df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWHsK7sK9jfr2UebBSADmpJNXN0ZCT7Gg',
    appId: '1:736853854569:ios:f6e3046acb6a206e2455f8',
    messagingSenderId: '736853854569',
    projectId: 'coin-control-44df7',
    storageBucket: 'coin-control-44df7.appspot.com',
    iosBundleId: 'com.example.coinControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWHsK7sK9jfr2UebBSADmpJNXN0ZCT7Gg',
    appId: '1:736853854569:ios:e628bb9caaddc34d2455f8',
    messagingSenderId: '736853854569',
    projectId: 'coin-control-44df7',
    storageBucket: 'coin-control-44df7.appspot.com',
    iosBundleId: 'com.example.coinControl.RunnerTests',
  );
}
